
name: CI
on: 
 workflow_dispatch:
 #push:
 #   branches:
 #     - master
 #     - Develop
 #pull_request:
 #   branches:
 #     - master
 #     - Develop

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions

env:
  AZURE_RESOURCE_GROUP: capweursgibad01   # set this to your Azure Resource group's name  
 
jobs:
  build:
    runs-on: ubuntu-latest
    name: Dotnet Side by Side testing sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.x'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - run: dotnet build ./src/IBA_Parquet/IBA_Parquet/IBA_Parquet.csproj
      - run: dotnet test ./src/IBA_Parquet/IBA_Parquet/IBA_Parquet.csproj

