name: test deploy web app ARM Template & code
on: workflow_dispatch

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions

env:
  AZURE_RESOURCE_GROUP: capweursgut1p01   # set this to your Azure Resource group's name  
  DOTNET_VERSION: '3.1.x'           # set this to the dot net version to use
  AZURE_WEBAPP_NAME: 'capweuwebut1d11ela'
  AZURE_WEBAPP_PACKAGE_PATH: './src/IBA_Parquet/IBA_Parquet'      # set this to the path to your web app project, defaults to the repository root
  #AZURE_WEBAPP_PUBLISH_PROFILE: '<publishData><publishProfile profileName="capweuwebut1d11ela - Web Deploy" publishMethod="MSDeploy" publishUrl="capweuwebut1d11ela.scm.azurewebsites.net:443" msdeploySite="capweuwebut1d11ela" userName="$capweuwebut1d11ela" userPWD="Nrwcf32W1ujezlgcAE43lmwFv7xhStHcRbSRmp1ge2sjn03XJawcBLmmFrtA" destinationAppUrl="http://capweuwebut1d11ela.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="capweuwebut1d11ela - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod-am2-481.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="capweuwebut1d11ela\$capweuwebut1d11ela" userPWD="Nrwcf32W1ujezlgcAE43lmwFv7xhStHcRbSRmp1ge2sjn03XJawcBLmmFrtA" destinationAppUrl="http://capweuwebut1d11ela.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="capweuwebut1d11ela - Zip Deploy" publishMethod="ZipDeploy" publishUrl="capweuwebut1d11ela.scm.azurewebsites.net:443" userName="$capweuwebut1d11ela" userPWD="Nrwcf32W1ujezlgcAE43lmwFv7xhStHcRbSRmp1ge2sjn03XJawcBLmmFrtA" destinationAppUrl="http://capweuwebut1d11ela.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>'
  
jobs:
  deploy-arm:
    runs-on: ubuntu-latest
    steps:
   
    # Checkout
    - name: Checkout
      uses: actions/checkout@v1          
    # Authentication
    # Set up the following secrets in your repository: AZURE_CREDENTIALS
    # For details on usage of secrets, please refer https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_DEVOPS  }}
     # Deploy eventgrid
    - name: Arm deploy Eventgrid
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        template: ./src/Azure/eventgrid.json
        parameters: ./src/Azure/eventgrid-dev.parameters.json
    # Deploy DataLake
    - name: Arm deploy DataLake
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        template: ./src/Azure/storageaccount.json
        parameters: ./src/Azure/storageaccount-dev.parameters.json
    # Deploy Web app
    - name: Arm deploy Web App
      uses: azure/arm-deploy@v1
      id: deploy
      with:
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        template: ./src/Azure/webapp.json
        parameters: ./src/Azure/webapp-dev.parameters.json
      env:
          AZURE_WEBAPP_PUBLISH_PROFILE: ${{ steps.deploy.outputs.webapppublishProfile }}
           
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
       dotnet-version: ${{ env.DOTNET_VERSION }} 
   
      # Run dotnet build and publish
    - name: dotnet build
      run: dotnet build ./src/IBA_Parquet/IBA_Parquet/IBA_Parquet.csproj --configuration Release
    - name: dotnet publish
      run: dotnet publish ./src/IBA_Parquet/IBA_Parquet/IBA_Parquet.csproj -c Release -o ./src/IBA_Parquet/IBA_Parquet/myapp

       # Deploy to Azure Web apps
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
         app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
         publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }} # get publish profile from output of arm
         package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
      # Deploy DataLake
    - name: Arm deploy Function
      uses: azure/arm-deploy@v1
      id: deployFunct
      with:
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        template: ./src/Azure/function.json
        parameters: ./src/Azure/function-dev.parameters.json
      env:
          AZURE_FUNCTION_PUBLISH_PROFILE: ${{ steps.deploy.outputs.functionpublishProfile }}