
name: workflow to deploy an ARM Template to a resource group
on: workflow_dispatch

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions

env:
  AZURE_RESOURCE_GROUP: capweursgibad01   # set this to your Azure Resource group's name  
 
  
jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
   
    # Checkout
    - name: Checkout
      uses: actions/checkout@v1          
    # Authentication
    # Set up the following secrets in your repository: AZURE_CREDENTIALS
    # For details on usage of secrets, please refer https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
   